bank/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('profiles.urls')),
    path('count', include('counts.urls')),
    path('admin/', admin.site.urls),
]

counts/urls.py
from django.urls import path

from . import views

app_name = 'counts'

urlpatterns = [
    path('deposit/', views.DepositView.as_view(), name='deposit'),
    path('withdraw/', views.WithdrawView.as_view(), name='withdraw')
]

profiles/urls.py
from django.urls import path

from . import views

app_name = 'profiles'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('checking/', views.CheckingView.as_view(), name='checking'),
    path('saving/', views.SavingsView.as_view(), name='saving'),
    path('juridical/', views.JuridicalView.as_view(), name='juridical'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('details/', views.DetailsView.as_view(), name='details'),
]

profiles/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import User

from utils.validacpf import valida_cpf

class Person(models.Model):
    BANK_NAMES = (
        ('NB', 'Não é um banco'),
        ('BB', 'Banco do Basil'),
        ('IT', 'Itaú'),
        ('CX', 'Caixa'),
        ('BD', 'Bradesco'),
        ('ST', 'Santander'),
        ('C6', 'C6 Bank'),
        ('BP', 'BTG Pactual'),
        ('NU', 'Nubank'),
        ('IN', 'Inter'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='User')
    date = models.DateField('Date create/Bday', )
    bank = models.CharField(
        max_length=14,
        default='NB',
        choices=BANK_NAMES
    )

    def clean(self):
        error_messages = {}

        if self.bank == 'NAB':
            error_messages['bank'] = 'Selecione um banco por favor!'

    class Meta:
        abstract = True

class Checking_Person(Person):
    cpf = models.CharField('CPF', max_length=11)
    count = models.OneToOneField('counts.Checking', on_delete=models.CASCADE, verbose_name='Checking count') 

    def clean(self):
        error_messages = {}

        if not valida_cpf(self.cpf):
            error_messages['cpf'] = 'Por favor digite um cpf válido!'

        if error_messages:
            raise ValidationError(error_messages)         
    
    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'

    class Meta:
        verbose_name = 'Checking'
        verbose_name_plural = 'Checking_people'

class Savings_Person(Person):
    cpf = models.CharField('CPF', max_length=11)
    count = models.OneToOneField('counts.Savings', on_delete=models.CASCADE, verbose_name='Saving count')

    def clean(self):
        error_messages = {}

        if not valida_cpf(self.cpf):
            error_messages['cpf'] = 'Por favor digite um cpf válido'

        if error_messages:
            raise ValidationError(error_messages)

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'        
        
    class Meta:
        verbose_name = 'Saving'
        verbose_name_plural = 'Savings'

class Legal_Person(Person):
    cnpj = models.CharField('CNPJ', max_length=18)
    indentification = models.CharField('Indentification', max_length=14)
    count = models.OneToOneField('counts.Legal', on_delete=models.CASCADE, verbose_name='Juridical count')

    def __str__(self):
        return self.user.first_name

    class Meta:
        verbose_name = 'Juridical'
        verbose_name_plural = 'Juridicals'

profiles/views.py
from django import forms
from django.shortcuts import get_object_or_404, render, redirect
from django.views import View
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from counts.models import Checking, Legal, Savings
from . import models
from . import forms

class IndexView(View):
    template_name = 'profiles/index.html'

    def get(self, *args, **kwargs):
        return render(self.request, self.template_name)

class CheckingView(View):
    template_name = 'profiles/checking.html'

    def setup(self, *args, **kwargs):
        super().setup(*args, **kwargs)

        self.profile = None

        if self.request.user.is_authenticated:
            self.profile = models.Checking_Person.objects.filter(user=self.request.user).first()
            
            self.context = {
                'userForm': forms.UserForm(data=self.request.POST or None, user=self.request.user, instance=self.request.user),
                'checkingPerson': forms.CheckingPersonForm(data=self.request.POST or None, instance=self.profile),
                'checkingCount': forms.CheckingForm(data=self.request.POST or None, instance=self.profile)
            }
        else:
            self.context = {
                'userForm': forms.UserForm(data=self.request.POST or None),
                'checkingPerson': forms.CheckingPersonForm(data=self.request.POST or None),
                'checkingCount': forms.CheckingForm(data=self.request.POST or None),
            }

        self.userForm = self.context['userForm']
        self.checkingPerson = self.context['checkingPerson']
        self.checkingCount = self.context['checkingCount']

        if self.request.user.is_authenticated:
            self.template_name = 'profiles/update.html'

        self.render = render(self.request, self.template_name, self.context)

    def post(self, *agrs, **kwargs):
        if not self.userForm.is_valid():
            return self.render
        else:
            username = self.userForm.cleaned_data.get('username')
            password = self.userForm.cleaned_data.get('password')
            email = self.userForm.cleaned_data.get('email')
            first_name = self.userForm.cleaned_data.get('first_name')
            last_name = self.userForm.cleaned_data.get('last_name')

            user = get_object_or_404(User, username=self.request.user.username)

            if password:
                user.set_password(password)

            user.email = email
            user.first_name = first_name
            if user.last_name:
                user.last_name = last_name
            user.save()
            
            if password:
                authenticates = authenticate(
                    self.request,
                    username=user,
                    password=password
                )

                if authenticates:
                    login(self.request, user=user)


        if not self.userForm.is_valid() or not self.checkingPerson.is_valid() or not self.checkingCount.is_valid():
            return self.render

        username = self.userForm.cleaned_data.get('username')
        password = self.userForm.cleaned_data.get('password')
        email = self.userForm.cleaned_data.get('email')
        first_name = self.userForm.cleaned_data.get('first_name')
        last_name = self.userForm.cleaned_data.get('last_name')
        
        # Logged user
        if self.request.user.is_authenticated:
            user = get_object_or_404(User, username=self.request.user.username)

            user.username = username

            if password:
                user.set_password(password)

            user.email = email

            user.first_name = first_name
            user.last_name = last_name
            user.save()

            if password:
                authenticates = authenticate(
                    self.request,
                    username=user,
                    password=password,
                )

                if authenticates:
                    login(self.request, user=user)
                    redirect('profiles:details')

            if not self.profile:
                self.checkingPerson.cleaned_data['user'] = user
                profile = models.Checking_Person(**self.checkingPerson.cleaned_data)
                profile.save()
            else:
                profile = self.checkingPerson.save(commit=False)
                profile.user = user
                profile.save()

            redirect('profiles:index')

        # New user
        else:
            user = self.userForm.save(commit=False)
            user.set_password(password)
            user.save()

            profile = self.checkingPerson.save(commit=False)
            profile.user = user 
            count = self.checkingCount.save()
            profile.count = count
            profile.save()

        if password:
            authenticates = authenticate(
                self.request,
                username=user,
                password=password,
            )

            if authenticates:
                login(self.request, user=user)
        
        return redirect('profiles:index')

    def get(self, *args, **kwargs):
        return self.render

class JuridicalView(View):
    template_name = 'profiles/juridical.html'

    def setup(self, *args, **kwargs):
        super().setup(*args, **kwargs)

        self.profile = None

        if self.request.user.is_authenticated:
            self.profile = models.Checking_Person.objects.filter(user=self.request.user).first()
            
            self.context = {
                'userJuridicalForm': forms.UserJuridicalForm(data=self.request.POST or None, user=self.request.user, instance=self.request.user),
                'juridicalPerson': forms.JuridicalPersonForm(data=self.request.POST or None, instance=self.profile),
                'juridicalCount': forms.LegalForm(data=self.request.POST or None, instance=self.profile)
            }
        else:
            self.context = {
                'userJuridicalForm': forms.UserJuridicalForm(data=self.request.POST or None),
                'juridicalPerson': forms.JuridicalPersonForm(data=self.request.POST or None),
                'juridicalCount': forms.LegalForm(data=self.request.POST or None),
                'type': 'juridical',
            }

        self.userForm = self.context['userJuridicalForm']
        self.juridicalPerson = self.context['juridicalPerson']
        self.juridicalCount = self.context['juridicalCount']

        if self.request.user.is_authenticated:
            self.template_name = 'profiles/update.html'

        self.render = render(self.request, self.template_name, self.context)

    def post(self, *agrs, **kwargs):
        if not self.userForm.is_valid() or not self.juridicalPerson.is_valid() or not self.juridicalCount:
            return self.render

        username = self.userForm.cleaned_data.get('username')
        password = self.userForm.cleaned_data.get('password')
        email = self.userForm.cleaned_data.get('email')
        first_name = self.userForm.cleaned_data.get('first_name')
        last_name = self.userForm.cleaned_data.get('last_name')
        
        # Logged user
        if self.request.user.is_authenticated:
            user = get_object_or_404(User, username=self.request.user.username)

            user.username = username

            if password:
                user.set_password(password)

            user.email = email

            user.first_name = first_name
            user.last_name = last_name
            user.save()

            if not self.profile:
                self.juridicalPerson.cleaned_data['user'] = user
                profile = models.Legal_Person(**self.juridicalPerson.cleaned_data)
                profile.save()
            else:
                profile = self.juridicalPerson.save(commit=False)
                profile.user = user
                profile.save()

            redirect('profiles:index')

        # New user
        else:
            user = self.userForm.save(commit=False)
            user.set_password(password)
            user.save()

            profile = self.juridicalPerson.save(commit=False)
            profile.user = user 
            count = self.juridicalCount.save()
            profile.count = count
            profile.save()

        if password:
            authenticates = authenticate(
                self.request,
                username=user,
                password=password,
            )

            if authenticates:
                login(self.request, user=user)
                
                
        return redirect('profiles:index')

    def get(self, *args, **kwargs):
        return self.render

class SavingsView(View):
    template_name = 'profiles/savings.html'

    def setup(self, *args, **kwargs):
        super().setup(*args, **kwargs)

        self.profile = None

        if self.request.user.is_authenticated:
            self.profile = models.Checking_Person.objects.filter(user=self.request.user).first()
            
            self.context = {
                'userForm': forms.UserForm(data=self.request.POST or None, user=self.request.user, instance=self.request.user),
                'savingsPerson': forms.SavingsPersonForm(data=self.request.POST or None),
                'savingsCount': forms.SavingsForm(data=self.request.POST or None)
            }
        else:
            self.context = {
                'userForm': forms.UserForm(data=self.request.POST or None),
                'savingsPerson': forms.SavingsPersonForm(data=self.request.POST or None),
                'savingsCount': forms.SavingsForm(data=self.request.POST or None),
                'type': 'savings',
            }

        self.userForm = self.context['userForm']
        self.savingsPerson = self.context['savingsPerson']
        self.savingsCount = self.context['savingsCount']

profiles/templates/partials/_footer.html
{% load static %}

<footer class="container-fluid bg-primary">
    <div class="container text-light">
        <div class="row">
            <div class="col">
                <div class="p-1">
                    <span class="align-middle p-1">Feito com Django</span>
                </div>
            </div>
            <div class="col">
                <div class="p-1 text-right">
                    <span class="align-middle p-1">Por Ernesto Santos</span>
                </div>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'bootstrap/js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script defer src="{% static 'font-awesome/js/all.js' %}"></script>
<script src="{% static 'custom/js/scripts.js' %}"></script>

profiles/templates/partials/_head.html
{% load static %}
    
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'custom/css/style.css' %}">

profiles/templates/partials/_messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

profiles/templates/partials/_nav.html
<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
    <a class="navbar-brand" href="{% url 'profiles:index' %}">Bank Manager</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profiles:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profiles:details' %}">Detalhes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'counts:deposit' %}">Depositar</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'counts:withdraw' %}">Sacar</a>
            </li>
            
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Conta
                </a>
                <div class="dropdown-menu nav-item" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'profiles:checking' %}" >Atualizar dados</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'profiles:logout' %}" >Log out</a>
                    <div class="dropdown-divider"></div>
                </div>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profiles:login' %}">Fazer login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profiles:checking' %}">Conta Corrente</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profiles:saving' %}">Conta Poupança</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profiles:juridical' %}">Conta Jurídica</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

profiles/templates/partials/_pagination.html
{% if is_paginated %}
<div class="pagination">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1">&laquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
        </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}

        {% if page_obj.number == num %}
        <li class="page-item active">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}

        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
        </li>
        {% endif %}
    </ul>
</div>
{% endif %}